sudo: required
services:
  - docker

script:
  - docker build -t dooodle/vis-mondial .
  - bash install-kubectl

after_script:
  - docker images

deploy:
  provider: script
  script:
    - bash docker_push
    - kubectl get pods
  on:
    branch: master
