sudo: required
services:
  - docker

script:
  - docker build -t dooodle/vis-mondial .
  - bash install-kubectl
  - bash docker_push
  - kubectl get pods

after_script:
  - docker images
  - kubectl get pods

deploy:
  provider: script
  script: kubectl get pods
  on:
    branch: master
