branches:
  only:
  - master

sudo: required
services:
  - docker
notifications:
  slack: dooodle:hots3bBY7zx3Dff7425iO67W

script:
  - docker build -t dooodle/vis-mondial .
  - bash install-kubectl
  - bash docker_push
  - kubectl get pods | grep mondial
  - kubectl patch deployment mondial-deployment -p   "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl get pods | grep mondial

