sudo: required
services:
  - docker

script:
  - docker build -t ilanpillemer/vis-mondial .

after_script:
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
